name: "multievent workflow pipeline/workflow"  # Name of the workflow

on:  # Event triggers
  push:
    branches:
      - master

jobs:
  on-push:  # Job name
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:  # Steps to be executed
      - name: "running on master push"
        run: echo "running on master push"
